tasks:
  - name: Install & Start Backend
    init: cd backend && npm install
    command: npm run start:dev
    
  - name: Install & Start Frontend
    init: cd frontend && npm install
    command: npm run start:gitpod

ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 4200
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - angular.ng-template
    - dbaeumer.vscode-eslint
